/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.itb.gui.progressbar;

import id.ac.itb.openie.dataprocessor.Dataprocessor;
import id.ac.itb.openie.dataprocessor.DataprocessorPipeline;
import org.apache.commons.lang3.StringUtils;

import javax.swing.*;


public class DataprocessorProgress extends javax.swing.JFrame {

    DataprocessorPipeline dataprocessorPipeline;
    private Timer processTimer = null;
    private int tick;
    private int counter = 0;

    /**
     * Creates new form ExtractorProgress
     */
    public DataprocessorProgress() {
        initComponents();
    }

    public DataprocessorProgress(DataprocessorPipeline dataprocessorPipeline) {
        this.dataprocessorPipeline = dataprocessorPipeline;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        dataprocessingDocumentsProgressLabel = new javax.swing.JLabel();
        dataprocessingPipelineProgressLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Running Dataprocessor\n for Data Training");

        showProgressLabel();

        processTimer = new Timer(30, e -> {
            showProgressLabel();
        });
        processTimer.start();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataprocessingPipelineProgressLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dataprocessingDocumentsProgressLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dataprocessingPipelineProgressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataprocessingDocumentsProgressLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
        setTitle("Dataprocessing Progress");
    }// </editor-fold>//GEN-END:initComponents

    private void showProgressLabel() {
        counter++;
        int totalCurrentlyDocumentsDataprocessed = dataprocessorPipeline.getCurrentlyDataprocessedDocuments();
        int totalDocumentsToBeDataprocessed = dataprocessorPipeline.getTotalDocumentsToBeDataprocessed();
        String dataprocessorName = "";
        String trail = StringUtils.repeat(".", tick) + StringUtils.repeat(" ", 4 - tick);

        if (counter % 10 == 0) {
            tick = (tick % 4) + 1;
        }

        if(!dataprocessorPipeline.isTraining()) jLabel1.setText("Running Dataprocessor\n for Data Set");

        
        if (dataprocessorPipeline.getCurrentlyRunningDataprocessor() != null) {
            dataprocessorName = ((Dataprocessor)dataprocessorPipeline.getCurrentlyRunningDataprocessor()).getDataprocessorHandler().getPluginName();
        }

        if (totalDocumentsToBeDataprocessed > 0 && totalCurrentlyDocumentsDataprocessed == totalDocumentsToBeDataprocessed) {
            dataprocessingDocumentsProgressLabel.setText("Dataprocessing Completed. Loading" + trail);
        } else {
            dataprocessingDocumentsProgressLabel.setText(" " + totalCurrentlyDocumentsDataprocessed + " / " + totalDocumentsToBeDataprocessed + " documents ");
        }

        updateProgressBar(totalCurrentlyDocumentsDataprocessed, totalDocumentsToBeDataprocessed);

        int totalProcessedDataprocessor = dataprocessorPipeline.getTotalProcessedDataprocessor();
        int totalDataprocessor = dataprocessorPipeline.getNumberOfDataprocessors();

        if (dataprocessorName.equalsIgnoreCase("")) {
            dataprocessingPipelineProgressLabel.setText("Setting up dataprocessors" + trail + StringUtils.repeat(" ", 40));
        } else {
            dataprocessingPipelineProgressLabel.setText("Running " + dataprocessorName + " ( " + totalProcessedDataprocessor + " / " + totalDataprocessor + " dataprocessor" + (totalDataprocessor > 1 ? "s" : "") + " )");
        }
    }

    private void updateProgressBar(int numerator, int denominator) {
        jProgressBar1.setMinimum(0);
        jProgressBar1.setMaximum(denominator);
        jProgressBar1.setValue(numerator);
    }

    public void stopTimer() {
        processTimer.stop();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataprocessorProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataprocessorProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataprocessorProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataprocessorProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataprocessorProgress().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataprocessingDocumentsProgressLabel;
    private javax.swing.JLabel dataprocessingPipelineProgressLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
